apiVersion: vpc.yandex-cloud.jet.crossplane.io/v1alpha1
kind: Network
metadata:
  name: new-vpc-n
spec:
  deletionPolicy: Orphan
  forProvider:
    folderId: <folder-id>
    name: new-vpc-n
  providerConfigRef:
    name: example
