apiVersion: vpc.yandex-cloud.jet.crossplane.io/v1alpha1
kind: SecurityGroupRule
metadata:
  name: example-sg-rule
spec:
  forProvider:
    securityGroupBinding: <sg-id>
    securityGroupId: <sg-id>
    direction: ingress
    port: 8080
    protocol: TCP
    description: "rule1 description"
  providerConfigRef:
    name: example
