apiVersion: iam.yandex-cloud.jet.crossplane.io/v1alpha1
kind: FolderIAMMember
metadata:
  name: lala19
spec:
  forProvider:
    folderId: <your-folder-id>
    role: storage.editor
    member: "serviceAccount:<sa-id>"
  providerConfigRef:
    name: example
