apiVersion: iam.yandex-cloud.jet.crossplane.io/v1alpha1
kind: FolderIAMBinding
metadata:
  name: admin-1998 # укажи своё название
spec:
  deletionPolicy: Orphan
  forProvider:
    folderId: <your-folder-id>
    role: admin # укажи требуемую роль
    members: ["serviceAccount:<sa-id>"]
  providerConfigRef:
    name: example
