apiVersion: compute.yandex-cloud.jet.crossplane.io/v1alpha1
kind: Instance
metadata:
  name: example-instance
spec:
  forProvider:
    folderId: <your-folder-id>
    name: example-instance
    platformId: standard-v3
    zone: ru-central1-a
    resources:
      - cores: 2
        memory: 4
    bootDisk:
      - initializeParams:
          # ubuntu 20.04
          # yc compute image list --folder-id standard-images | grep 'ubuntu-20-04-lts'
          - imageId: fd8ot0k0vde438jv0t8j # your image-id
    networkInterface:
      - subnetId: <your-subnet-id>
    metadata:
      ssh-keys: "ubuntu:<public-key-data>"
  providerConfigRef:
    name: example
