apiVersion: dns.yandex-cloud.jet.crossplane.io/v1alpha1
kind: Recordset
metadata:
  name: apps
spec:
  deletionPolicy: Orphan
  forProvider:
    data:
      - '<ip-address>' # тут должен быть ip-адрес
    name: '*.apps.pushka.ga.' # поменяй на свой домен
    ttl: 600
    type: A
    zoneId: <zone-id> # поменяй на имя своей зоны
  providerConfigRef:
    name: example
