apiVersion: dns.yandex-cloud.jet.crossplane.io/v1alpha1
kind: Zone
metadata:
  name: yc-courses-1999
spec:
  deletionPolicy: Orphan
  forProvider:
    folderId: <your-folder-id>
    name: yc-courses-1999 # укажи имя своей dns-зоны
    public: true
    zone: pushka.ga. # укажи свою dns-зону
  providerConfigRef:
    name: example
